<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\FIC\Documents\backend\POO\aula 07\Heranca\Heranca\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\FIC\Documents\backend\POO\aula 07\Heranca\Heranca\.editorconfig" />
  </ItemGroup>

</Project>
